# Generated by Django 5.0.2 on 2024-04-03 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issued_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
