# Generated by Django 5.0.2 on 2024-04-05 01:25

import datetime
import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_book_id_transaction_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='late_fee',
            field=models.IntegerField(default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.ExtractDay(models.DateField(default=None), models.DateField(default=datetime.date(2024, 1, 1))), '*', models.Value(10))),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returned_date',
            field=models.DateField(default=None),
        ),
    ]
