# Generated by Django 5.0.2 on 2024-04-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_late_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='late_fee',
            new_name='due',
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returned_date',
            field=models.DateField(null=True),
        ),
    ]
