# Generated by Django 5.0.2 on 2024-04-07 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_late_fee_transaction_due_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(default=models.DateField(default=datetime.date(2024, 1, 1)), null=True),
        ),
    ]
