# Generated by Django 5.0.2 on 2024-04-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='returned_date',
            field=models.DateField(null=True),
        ),
    ]
