# Generated by Django 5.0.2 on 2024-04-10 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_transaction_due_alter_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 7, 1, 1, 904940)),
        ),
    ]
