# Generated by Django 5.0.2 on 2024-04-10 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_alter_transaction_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 7, 38, 21, 716932)),
        ),
    ]
