# Generated by Django 5.0.2 on 2024-04-19 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_alter_transaction_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_date',
            field=models.DateField(default=datetime.date(2024, 4, 19)),
        ),
    ]
