# Generated by Django 5.0.2 on 2024-03-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
