# Generated by Django 5.0.2 on 2024-03-12 00:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='ISBN', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=datetime.date(1990, 10, 10)),
        ),
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='author', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=datetime.date(1990, 10, 10)),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='publisher', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.category')),
            ],
        ),
    ]
