# Generated by Django 5.0.2 on 2024-03-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
