# Generated by Django 5.0.2 on 2024-03-12 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 12, 1, 48, 38, 279572, tzinfo=datetime.timezone.utc)),
        ),
    ]
