# Generated by Django 5.0.2 on 2024-03-17 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpublisher',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookpublisher',
            name='publisher',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(through='book.BookAuthor', to='book.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='book.BookAuthor', to='book.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='book.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(related_name='publishers', to='book.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=datetime.date(2024, 3, 17)),
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
        migrations.DeleteModel(
            name='BookPublisher',
        ),
    ]
