# Generated by Django 5.0.2 on 2024-04-03 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_remove_book_published_date_book_published_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=datetime.date(2024, 4, 3)),
        ),
    ]
