# Generated by Django 5.0.2 on 2024-04-10 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_alter_book_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=datetime.date(2024, 4, 10)),
        ),
    ]
