# Generated by Django 5.0.2 on 2024-04-19 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_book_shelf_no_alter_book_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 6, 47, 54, 372386, tzinfo=datetime.timezone.utc)),
        ),
    ]
