# Generated by Django 5.0.2 on 2024-04-10 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_book_shelf_no_alter_book_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default='category', on_delete=django.db.models.deletion.CASCADE, to='book.category'),
        ),
    ]
