# Generated by Django 5.0.2 on 2024-04-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_remove_book_category_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='book.category'),
        ),
    ]
